selected:
  # - configs/topology_dmz_segmented.yaml
  - configs/topology_enterprise.yaml
  # - configs/topology_insider_threat.yaml
  # - configs/topology_remote_worker.yaml
  # - configs/topology_three_site.yaml
  # - configs/topology_wan_isp.yaml
  # - configs/topology.yaml
repeat: 1

vpn:
  - on
  # - off

npc:
  # - low
  - medium
  # - high

inject:
  - on
  # - off

exfil:
  # - on
  - off
